[project]
name = "test-app"
version = "0.1.0"
description = "A short description of my project"
readme = "README.md"
dependencies = [
    "django==5.2.11",
    "django-tailwind[cookiecutter,reload]>=4.5.0",
    "django-tailwind-cli>=4.7.0",
]

[dependency-groups]
dev = [
    "django-debug-toolbar>=7.1.0",
]
